resource_registry:
  OS::TripleO::Services::Rhsm: /usr/share/openstack-tripleo-heat-templates/deployment/rhsm/rhsm-baremetal-ansible.yaml

parameter_defaults:
  RhsmVars:
    rhsm_activation_key: "OSP16LTS"
    rhsm_method: "satellite"
    rhsm_org_id: "Moria-Lab"
    rhsm_server_hostname: "gandalf.consulting-services.lan"
    rhsm_baseurl: "https://gandalf.consulting-services.lan/pulp/repos"
    rhsm_release: 8.2

