parameter_defaults:
  # Enable various IPv6 features in Nova.
  #NovaIPv6: False
  OvsPmdCoreList: "6,7"   #"3,5,43,45" VZ specifc PMD on same NUMA as NIC and NIC both ports bonded
  OvsDpdkMemoryChannels: "2"  #"4" Vz specific

  ComputeExtraConfig:
    nova::cpu_allocation_ratio: 1.0
    nova::scheduler::filter::cpu_allocation_ratio: 1.0
    nova::initial_ram_allocation_ratio: 1.0
    nova::ram_allocation_ratio: 1.0
    nova::scheduler::filter::ram_allocation_ratio: 1.0
    nova::compute::allow_resize_to_same_host: true
    nova::compute::resume_guests_state_on_host_boot: true
    nova::compute::resize_confirm_window: 1

  ComputeOvsDpdkExtraConfig:
    nova::cpu_allocation_ratio: 1.0
    nova::scheduler::filter::cpu_allocation_ratio: 1.0
    nova::initial_ram_allocation_ratio: 1.0
    nova::ram_allocation_ratio: 1.0
    nova::scheduler::filter::ram_allocation_ratio: 1.0
    nova::compute::allow_resize_to_same_host: true
    nova::compute::resume_guests_state_on_host_boot: true
    nova::compute::resize_confirm_window: 1

  ComputeSriovExtraConfig:
    nova::cpu_allocation_ratio: 1.0
    nova::scheduler::filter::cpu_allocation_ratio: 1.0
    nova::initial_ram_allocation_ratio: 1.0
    nova::ram_allocation_ratio: 1.0
    nova::scheduler::filter::ram_allocation_ratio: 1.0
    nova::compute::allow_resize_to_same_host: true
    nova::compute::resume_guests_state_on_host_boot: true
    nova::compute::resize_confirm_window: 1

  ComputeOvsDpdkSriovExtraConfig:
    nova::cpu_allocation_ratio: 1.0
    nova::scheduler::filter::cpu_allocation_ratio: 1.0
    nova::initial_ram_allocation_ratio: 1.0
    nova::ram_allocation_ratio: 1.0
    nova::scheduler::filter::ram_allocation_ratio: 1.0
    nova::compute::allow_resize_to_same_host: true
    nova::compute::resume_guests_state_on_host_boot: true
    nova::compute::resize_confirm_window: 1

  ComputeParameters:
    #KernelArgs: "default_hugepagesz=1G hugepagesz=1G"
    NovaReservedHostMemory: 4096
    OvsHwOffload: false

  ComputeOvsDpdkParameters:
    #KernelArgs: "default_hugepagesz=1G hugepagesz=1G hugepages=32 intel_iommu=on iommu=pt rcu_nocb_poll"
    KernelArgs: "default_hugepagesz=1G hugepagesz=1G hugepages=32 intel_iommu=on iommu=pt"
    OvsHwOffload: false
    NovaReservedHostMemory: 4096
    NovaComputeCpuSharedSet: "0-5,12-17"
    NovaComputeCpuDedicatedSet: "6-11,18-23"
    # 0-0       0,1     12,13
    # 0-1       2,3     14,15
    # 0-2       4,5     16,17
    # 0-8       6,7     18,19
    # 0-9       8,9      20,21
    # 0-10      10,11   22,23
    #IsolCpusList: "6-11,18-23"
    OvsDpdkSocketMemory: "1024,4096"

  ComputeSriovParameters:
    KernelArgs: "default_hugepagesz=1GB hugepagesz=1G hugepages=32 intel_iommu=on iommu=pt"
    OvsHwOffload: false
    #TunedProfileName: "cpu-partitioning"
    NeutronPhysicalDevMappings:
      - tenant:enp4s0f0
      - tenant:enp4s0f1
    # Need to edit per hardware confguration
    #NovaPCIPassthrough:
    #  - vendor_id: "<vendor_id>"
    #    product_id: "<product_id>"
    #    address: "<NIC_address>"
    #    physical_network: "<physical_network>"
    #  - devname: "eno3"
    #    trusted: "true"
    #    physical_network: "sriov1"
    #  - devname: "eno4"
    #    trusted: "true"
    #    physical_network: "sriov2"
    NovaReservedHostMemory: 4096
    # Need to edit per hardware confguration
    NovaComputeCpuSharedSet: "0-5,12-17"
    NovaComputeCpuDedicatedSet: "6-11,18-23"
    # 0-0       0,1     12,13
    # 0-1       2,3     14,15
    # 0-2       4,5     16,17
    # 0-8       6,7     18,19
    # 0-9       8,9      20,21
    # 0-10      10,11   22,23

  ComputeOvsDpdkSriovParameters:
    #KernelArgs: "default_hugepagesz=1G hugepagesz=1G hugepages=32 intel_iommu=on iommu=pt rcu_nocb_poll"
    KernelArgs: "default_hugepagesz=1G hugepagesz=1G hugepages=32 intel_iommu=on iommu=pt"
    OvsHwOffload: false
    #TunedProfileName: "cpu-partitioning"
    NeutronPhysicalDevMappings:
      - tenant:enp4s0f0
      - tenant:enp4s0f1
    # Need to edit per hardware confguration
    #NovaPCIPassthrough:
    #  - vendor_id: "<vendor_id>"
    #    product_id: "<product_id>"
    #    address: "<NIC_address>"
    #    physical_network: "<physical_network>"
    #  - devname: "eno3"
    #    trusted: "true"
    #    physical_network: "sriov1"
    #  - devname: "eno4"
    #    trusted: "true"
    #    physical_network: "sriov2"
    NovaReservedHostMemory: 4096
    # Need to edit per hardware confguration
    NovaComputeCpuSharedSet: "0-5,12-17"
    NovaComputeCpuDedicatedSet: "6-11,18-23"
    # 0-0       0,1     12,13
    # 0-1       2,3     14,15
    # 0-2       4,5     16,17
    # 0-8       6,7     18,19
    # 0-9       8,9      20,21
    # 0-10      10,11   22,23
    #IsolCpusList: "6-11,18-23"
    OvsDpdkSocketMemory: "1024,4096"

