parameter_defaults:

  # Enable PCS IPv6
  CorosyncIPv6: False

  # Enable IPv6 environment for RabbitMQ.
  RabbitIPv6: False

  # Enable IPv6 environment for Memcached.
  MemcachedIPv6: False

  # Enable IPv6 environment for MySQL.
  MysqlIPv6: False

  # Enable IPv6 environment for Redis.
  RedisIPv6: False

  ControllerExtraConfig:
    nova::scheduler::filter::ram_weight_multiplier: -10.0
    heat::config::heat_config:
      DEFAULT/max_stacks_per_tenant:
        value: '100'
    neutron::config::server_config:
      DEFAULT/max_fixed_ips_per_port:
        value: 20
    neutron::max_allowed_address_pair: 20
    nova::api::auth_version: 'v3'
    horizon::horizon_upload_mode: "'direct'"
    tripleo::haproxy::ssl_cipher_suite: 'ECDHE+aRSA+AES256+GCM+SHA384:ECDHE+aRSA+AES128+GCM+SHA256:ECDHE+aRSA+AES256+SHA384:ECDHE+aRSA+AES128+SHA256:AES256+GCM+SHA384:AES128+GCM+SHA256:AES128+SHA256:AES256+SHA256:HIGH:!aNULL:!eNULL:!LOW:!3DES:!MD5:!EXP:!PSK:!SRP:!DSS:!SHA'
    tripleo::haproxy::ssl_options: 'no-sslv3 no-tls-tickets no-tlsv10 no-tlsv11'
    tripleo::haproxy::mysql_max_conn: 8192
    apache::trace_enable: Off
    apache::vhost::options: ['FollowSymLinks','MultiViews']
    glance::config::api_config:
      cors/allowed_origin:
        value: https://service.%{hiera('tripleo::clouddomain')}
      cors/allow_credentials:
        value: true
      cors/expose_headers:
        value: 'X-Image-Meta-Checksum,X-Auth-Token,X-Subject-Token,X-Service-Token,X-OpenStack-Request-ID'
      cors/max_age:
        value: 3600
      cors/allow_methods:
        value: 'PUT'
      cors/allow_headers:
        value: 'Content-MD5,X-Image-Meta-Checksum,X-Storage-Token,Accept-Encoding,X-Auth-Token,X-Identity-Status,X-Roles,X-Service-Catalog,X-User-Id,X-Tenant-Id,X-OpenStack-Request-ID'
    #cinder::api::default_volume_type: tripleo_ceph

